
-- EEMS 第一版数据库建表脚本
-- MySQL 8.x / InnoDB / utf8mb4
-- 本文件仅包含建表语句，不包含初始化数据和执行命令。

CREATE TABLE IF NOT EXISTS `admin_user` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键，Java 对应 Long',
    `username` VARCHAR(50) NOT NULL COMMENT '登录账号',
    `password_hash` VARCHAR(255) NOT NULL COMMENT 'BCrypt 密码哈希，不保存明文密码',
    `nickname` VARCHAR(100) NOT NULL COMMENT '管理员显示名称',
    `avatar_url` VARCHAR(500) NULL COMMENT '头像地址',
    `role_code` VARCHAR(50) NOT NULL COMMENT '角色编码：SUPER_ADMIN、EDITOR',
    `status` VARCHAR(20) NOT NULL DEFAULT 'ENABLED' COMMENT '账号状态：ENABLED、DISABLED',
    `last_login_at` DATETIME NULL COMMENT '最近登录时间',
    `last_login_ip` VARCHAR(64) NULL COMMENT '最近登录 IP 地址',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_admin_user_username` (`username`),
    KEY `idx_admin_user_role_status` (`role_code`, `status`),
    KEY `idx_admin_user_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='管理员账号表';

CREATE TABLE IF NOT EXISTS `exhibition` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键，Java 对应 Long',
    `exhibition_code` VARCHAR(100) NOT NULL COMMENT '展会业务编码',
    `title` VARCHAR(200) NOT NULL COMMENT '展会标题',
    `subtitle` VARCHAR(200) NULL COMMENT '展会副标题',
    `year` SMALLINT NOT NULL COMMENT '举办年份',
    `edition` VARCHAR(50) NULL COMMENT '届次，例如第二十一届',
    `cover_url` VARCHAR(500) NULL COMMENT '展会封面图地址',
    `summary` TEXT NULL COMMENT '展会简介',
    `description` LONGTEXT NULL COMMENT '展会详细描述，支持富文本',
    `venue` VARCHAR(200) NULL COMMENT '展馆或举办地点',
    `address` VARCHAR(500) NULL COMMENT '详细地址',
    `start_at` DATETIME NOT NULL COMMENT '展会开始时间',
    `end_at` DATETIME NOT NULL COMMENT '展会结束时间',
    `status` VARCHAR(20) NOT NULL DEFAULT 'DRAFT' COMMENT '展会状态：DRAFT、PUBLISHED、OFFLINE',
    `show_on_home` TINYINT NOT NULL DEFAULT 0 COMMENT '是否显示在首页：0 否，1 是',
    `home_sort` INT NOT NULL DEFAULT 0 COMMENT '首页排序值，数值越小越靠前',
    `published_at` DATETIME NULL COMMENT '发布时间',
    `contact_name` VARCHAR(100) NULL COMMENT '展会联系人',
    `contact_phone` VARCHAR(30) NULL COMMENT '展会联系电话',
    `registration_url` VARCHAR(500) NULL COMMENT '报名地址',
    `extra_data` JSON NULL COMMENT '扩展属性 JSON',
    `created_by` BIGINT UNSIGNED NULL COMMENT '创建人，关联 admin_user.id',
    `updated_by` BIGINT UNSIGNED NULL COMMENT '最后修改人，关联 admin_user.id',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_exhibition_code` (`exhibition_code`),
    KEY `idx_exhibition_status_start_at` (`status`, `start_at`),
    KEY `idx_exhibition_home_sort` (`show_on_home`, `home_sort`),
    KEY `idx_exhibition_year` (`year`),
    KEY `idx_exhibition_created_by` (`created_by`),
    CONSTRAINT `fk_exhibition_created_by` FOREIGN KEY (`created_by`) REFERENCES `admin_user` (`id`) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT `fk_exhibition_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `admin_user` (`id`) ON DELETE SET NULL ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='展会信息表';

CREATE TABLE IF NOT EXISTS `site_config` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键，Java 对应 Long',
    `config_code` VARCHAR(50) NOT NULL DEFAULT 'default' COMMENT '配置标识，单站点默认为 default',
    `current_exhibition_id` BIGINT UNSIGNED NULL COMMENT '当前主展会 ID，关联 exhibition.id',
    `site_title` VARCHAR(200) NOT NULL COMMENT '站点标题',
    `site_subtitle` VARCHAR(200) NULL COMMENT '站点副标题',
    `domain` VARCHAR(255) NULL COMMENT '站点域名',
    `logo_url` VARCHAR(500) NULL COMMENT '站点 Logo 地址',
    `keywords` VARCHAR(500) NULL COMMENT 'SEO 关键词',
    `description` TEXT NULL COMMENT 'SEO 描述',
    `icp_number` VARCHAR(100) NULL COMMENT '备案号',
    `template_code` VARCHAR(100) NULL COMMENT '模板编码，例如 coatingfair',
    `statistics_code` TEXT NULL COMMENT '统计代码',
    `footer_info` TEXT NULL COMMENT '页脚信息',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_site_config_code` (`config_code`),
    KEY `idx_site_config_current_exhibition` (`current_exhibition_id`),
    CONSTRAINT `fk_site_config_current_exhibition` FOREIGN KEY (`current_exhibition_id`) REFERENCES `exhibition` (`id`) ON DELETE SET NULL ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='站点配置表';

CREATE TABLE IF NOT EXISTS `company_profile` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键，Java 对应 Long',
    `profile_code` VARCHAR(50) NOT NULL DEFAULT 'default' COMMENT '配置标识，单站点默认为 default',
    `company_name` VARCHAR(200) NOT NULL COMMENT '公司名称',
    `address` VARCHAR(500) NULL COMMENT '公司地址',
    `postal_code` VARCHAR(20) NULL COMMENT '邮政编码',
    `contact_name` VARCHAR(100) NULL COMMENT '联系人',
    `mobile` VARCHAR(30) NULL COMMENT '手机号',
    `telephone` VARCHAR(30) NULL COMMENT '电话',
    `fax` VARCHAR(30) NULL COMMENT '传真',
    `email` VARCHAR(150) NULL COMMENT '电子邮箱',
    `qq` VARCHAR(50) NULL COMMENT 'QQ 号码',
    `wechat_image_url` VARCHAR(500) NULL COMMENT '微信二维码或图标地址',
    `business_license_no` VARCHAR(100) NULL COMMENT '营业执照号码',
    `other_info` TEXT NULL COMMENT '其他信息',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_company_profile_code` (`profile_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='公司信息表';

CREATE TABLE IF NOT EXISTS `cms_category` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键，Java 对应 Long',
    `parent_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '父栏目 ID，0 表示顶级栏目',
    `name` VARCHAR(100) NOT NULL COMMENT '栏目名称',
    `code` VARCHAR(100) NOT NULL COMMENT '栏目编码，全局唯一',
    `url_name` VARCHAR(150) NULL COMMENT '公共端 URL 名称',
    `model_code` VARCHAR(50) NOT NULL DEFAULT 'ARTICLE' COMMENT '内容模型：PAGE、ARTICLE、PRODUCT、CASE、LINK、DIRECTORY',
    `list_template` VARCHAR(100) NULL COMMENT '列表页模板编码',
    `detail_template` VARCHAR(100) NULL COMMENT '详情页模板编码',
    `sort_order` INT NOT NULL DEFAULT 0 COMMENT '栏目排序值，数值越小越靠前',
    `is_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用：0 否，1 是',
    `show_in_nav` TINYINT NOT NULL DEFAULT 1 COMMENT '是否显示在公共端导航：0 否，1 是',
    `link_url` VARCHAR(500) NULL COMMENT 'LINK 类型栏目跳转地址',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_cms_category_code` (`code`),
    KEY `idx_cms_category_parent_sort` (`parent_id`, `sort_order`),
    KEY `idx_cms_category_enabled_nav` (`is_enabled`, `show_in_nav`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='内容栏目表';

CREATE TABLE IF NOT EXISTS `cms_content` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键，Java 对应 Long',
    `category_id` BIGINT UNSIGNED NOT NULL COMMENT '所属栏目 ID，关联 cms_category.id',
    `exhibition_id` BIGINT UNSIGNED NULL COMMENT '所属展会 ID，关联 exhibition.id',
    `title` VARCHAR(200) NOT NULL COMMENT '内容标题',
    `slug` VARCHAR(150) NULL COMMENT '公共端 URL 标识',
    `cover_url` VARCHAR(500) NULL COMMENT '内容封面图地址',
    `summary` TEXT NULL COMMENT '内容摘要',
    `body` LONGTEXT NULL COMMENT '正文内容，支持富文本',
    `author` VARCHAR(100) NULL COMMENT '作者',
    `source` VARCHAR(200) NULL COMMENT '内容来源',
    `status` VARCHAR(20) NOT NULL DEFAULT 'DRAFT' COMMENT '内容状态：DRAFT、PUBLISHED、OFFLINE',
    `published_at` DATETIME NULL COMMENT '发布时间',
    `sort_order` INT NOT NULL DEFAULT 0 COMMENT '内容排序值，数值越小越靠前',
    `is_top` TINYINT NOT NULL DEFAULT 0 COMMENT '是否置顶：0 否，1 是',
    `is_recommend` TINYINT NOT NULL DEFAULT 0 COMMENT '是否推荐：0 否，1 是',
    `view_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '浏览次数',
    `extra_data` JSON NULL COMMENT '扩展属性 JSON',
    `created_by` BIGINT UNSIGNED NULL COMMENT '创建人，关联 admin_user.id',
    `updated_by` BIGINT UNSIGNED NULL COMMENT '最后修改人，关联 admin_user.id',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_cms_content_slug` (`slug`),
    KEY `idx_cms_content_category_status_publish` (`category_id`, `status`, `published_at`),
    KEY `idx_cms_content_exhibition_status_publish` (`exhibition_id`, `status`, `published_at`),
    KEY `idx_cms_content_recommend_sort` (`is_recommend`, `is_top`, `sort_order`),
    KEY `idx_cms_content_created_by` (`created_by`),
    CONSTRAINT `fk_cms_content_category` FOREIGN KEY (`category_id`) REFERENCES `cms_category` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT `fk_cms_content_exhibition` FOREIGN KEY (`exhibition_id`) REFERENCES `exhibition` (`id`) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT `fk_cms_content_created_by` FOREIGN KEY (`created_by`) REFERENCES `admin_user` (`id`) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT `fk_cms_content_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `admin_user` (`id`) ON DELETE SET NULL ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='栏目内容表';

CREATE TABLE IF NOT EXISTS `file_asset` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键，Java 对应 Long',
    `original_name` VARCHAR(255) NOT NULL COMMENT '原始文件名',
    `storage_name` VARCHAR(255) NOT NULL COMMENT '存储文件名',
    `file_url` VARCHAR(500) NOT NULL COMMENT '文件访问地址',
    `file_type` VARCHAR(100) NOT NULL COMMENT '文件 MIME 类型或扩展名',
    `file_size` BIGINT UNSIGNED NOT NULL COMMENT '文件大小，单位字节',
    `file_hash` VARCHAR(100) NULL COMMENT '文件哈希，可用于去重',
    `uploaded_by` BIGINT UNSIGNED NULL COMMENT '上传人，关联 admin_user.id',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除',
    PRIMARY KEY (`id`),
    KEY `idx_file_asset_hash` (`file_hash`),
    KEY `idx_file_asset_type_created` (`file_type`, `created_at`),
    KEY `idx_file_asset_uploaded_by` (`uploaded_by`),
    CONSTRAINT `fk_file_asset_uploaded_by` FOREIGN KEY (`uploaded_by`) REFERENCES `admin_user` (`id`) ON DELETE SET NULL ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文件资源表';

CREATE TABLE IF NOT EXISTS `guestbook` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键，Java 对应 Long',
    `name` VARCHAR(100) NOT NULL COMMENT '留言人姓名',
    `phone` VARCHAR(30) NULL COMMENT '联系电话',
    `email` VARCHAR(150) NULL COMMENT '联系邮箱',
    `company_name` VARCHAR(200) NULL COMMENT '公司名称',
    `message` TEXT NOT NULL COMMENT '留言内容',
    `status` VARCHAR(20) NOT NULL DEFAULT 'UNREAD' COMMENT '留言状态：UNREAD、READ、REPLIED、CLOSED',
    `reply_content` TEXT NULL COMMENT '管理员回复内容',
    `replied_by` BIGINT UNSIGNED NULL COMMENT '回复人，关联 admin_user.id',
    `replied_at` DATETIME NULL COMMENT '回复时间',
    `ip_address` VARCHAR(64) NULL COMMENT '提交 IP 地址',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除',
    PRIMARY KEY (`id`),
    KEY `idx_guestbook_status_created_at` (`status`, `created_at`),
    KEY `idx_guestbook_phone` (`phone`),
    KEY `idx_guestbook_replied_by` (`replied_by`),
    CONSTRAINT `fk_guestbook_replied_by` FOREIGN KEY (`replied_by`) REFERENCES `admin_user` (`id`) ON DELETE SET NULL ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='在线留言表';

CREATE TABLE IF NOT EXISTS `operation_log` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键，Java 对应 Long',
    `admin_user_id` BIGINT UNSIGNED NULL COMMENT '操作人 ID，关联 admin_user.id',
    `username` VARCHAR(50) NULL COMMENT '操作账号快照',
    `module` VARCHAR(50) NOT NULL COMMENT '业务模块',
    `operation` VARCHAR(100) NOT NULL COMMENT '操作名称',
    `request_method` VARCHAR(10) NULL COMMENT 'HTTP 请求方法',
    `request_url` VARCHAR(500) NULL COMMENT '请求地址',
    `request_ip` VARCHAR(64) NULL COMMENT '请求 IP 地址',
    `request_params` JSON NULL COMMENT '请求参数，敏感字段必须脱敏',
    `result` VARCHAR(20) NOT NULL DEFAULT 'SUCCESS' COMMENT '操作结果：SUCCESS、FAILURE',
    `error_message` VARCHAR(500) NULL COMMENT '失败原因',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除',
    PRIMARY KEY (`id`),
    KEY `idx_operation_log_user_created` (`admin_user_id`, `created_at`),
    KEY `idx_operation_log_module_operation` (`module`, `operation`),
    KEY `idx_operation_log_result_created` (`result`, `created_at`),
    CONSTRAINT `fk_operation_log_admin_user` FOREIGN KEY (`admin_user_id`) REFERENCES `admin_user` (`id`) ON DELETE SET NULL ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='操作日志表';
